version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    env_file:
      - .env
    ports:
      - '3333:3333'
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
